### PR TITLE
Publish transformations in periodic timer callback

### PR DESCRIPTION
**Pull request by orikuma**
This PR is divided part 2 of #893 
This PR separates publishing transformations into periodic timer callback to supress /tf rate at tf_rate param (default 50) but no new functions are included.

### CODE REVIEW

**Comment by snozawa** [comment]
As https://github.com/start-jsk/rtmros_common/pull/899, 
could you tell us which parts need `eigen_conversions` and `tf_conversions`?

As the comment https://github.com/start-jsk/rtmros_common/pull/899#issuecomment-170242941,
original data in this program OpenRTM+OpenHRP3 style and almost all "Transformation" calculation can be done by OpenHRP3 style.
We just need to output converted data into `odom` of `tf`, so i think we do not need to add additional dependency on `eigen_conversion` and `tf_conversion` in order to convert "Transformation".

**Comment by orikuma** [comment]
(1) Basic idea
In this and following PRs, transformations are converted as follows: `Eigen::Affine3d`(or `Eigen::Matrix33`, `Eigen::Vector3` and so on) -> `tf::Transform` -> `geometry_msgs::Transform`.
`eigen_conversion` is used in the first conversion and `tf_conversion` is used in the second conversion.

(2) Implementation details
The main purpose of this PR is not only converting `/odom` into `tf` but also suppressing rate of /tf. Therefore, I separated /tf publishing functions into periodicTimerCallback to isolate /tf related functions from main onExecute loop. 

- (2-a) About `eigen_conversions`
I adopted tf::Transform class as member variables to pass the transformations from main loop to periodicTimerCallback because Eigen classes may cause following alignment issues (cf. http://eigen.tuxfamily.org/dox-devel/group__TopicStructHavingEigenMembers.html).
I'm not  sure but this type of problems seems to depends on system (this problem did not occurred in my laptop but  caused compile error in jaxon).

- (2-b) About `tf_conversions`
`tf_conversions` provides conversions from tf class to geometry_msgs class. I think using these libraries are useful to prevent msg insert mistakes (like forgetting timestamp or quaternion order).

(c) Alternative implementations
- We can remove `tf_conversion` dependency by removing `tf::Transform` class and using `Eigen::Affine3d` and so on. I think we have to use `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` macro in that case but I don't sure that this cause another problems or not. (However, components in hrpsys-base like ImpedanceController has Eigen classes as structure or class members. How do you avoid this problem? Some compilation options are needed?)
- `eigen_conversion` also provides `Eigen::Affine3d` -> `geometry_msgs::Transform` conversions. I think it is better that using libraries than directly insert to msg members to prevent insert mistakes. It can be removed if we insert members of msg directly but then we have to pay attention to these mistakes.

**Comment by orikuma** [comment]
PS.
In this PR, `eigen_conversions` are not used (only used in https://github.com/start-jsk/rtmros_common/pull/896/files#diff-ac73db3c66ec2afe6e6410a14af1ebc0R821 but it is meaningless) and this is my fault in dividing PRs.
It will be used in updateGroundTransform or upateBodyOnOdom in later PRs so I think `eigen_conversions` should be removed and added in later PRs.

**Comment by orikuma** [comment]
I'm sorry that I have some misunderstanding in `eigen_conversions`and `tf_conversions`. I will fix and rewrite the comments.

**Comment by orikuma** [comment]
I fixed my wrong comment.
I misunderstood that `eigen_conversions` provides conversions from eigen to tf and `tf_conversions` provides conversions from tf class to geometry_msgs class but correctly, `eigen_conversions` provides conversions from eigen to geometry_msgs and `tf_conversions` provides conversions from eigen to tf class.

---
(1) Basic idea
In this and following PRs, transformations are converted as follows: `Eigen::Affine3d`(or `Eigen::Matrix33`, `Eigen::Vector3` and so on) -> `tf::Transform` -> `geometry_msgs::Transform`.
`eigen_conversion` provides `Eigen::Affine3d` -> `geometry_msgs::Transform` and `tf_conversion` provides `Eigen::Affine3d` -> `tf::Transform`.Therefore, `eigen_conversion` does not necessary in this and following PR (`tf::Transfrom`->`geometry_msgs::Transform` is supported by tf libraries).
The reason why `tf::Transform` is needed is described in (2).

(2) Implementation details
The main purpose of this PR is not only converting `/odom` into `tf` but also suppressing rate of /tf. Therefore, I separated /tf publishing functions into periodicTimerCallback to isolate /tf related functions from main onExecute loop. 

- (2-a) About `tf_conversions`
I adopted `tf::Transform` class as member variables to pass the transformations from main loop to periodicTimerCallback because Eigen classes may cause following alignment issues (cf. http://eigen.tuxfamily.org/dox-devel/group__TopicStructHavingEigenMembers.html).
I'm not  sure but this type of problems seems to depends on system (this problem did not occurred in my laptop but  caused compile error in jaxon).
`tf_conversions` provides conversions from eigen class to tf class. I think using these libraries are useful to prevent msg insert mistakes (like forgetting timestamp or quaternion order).

- (2-b) About `eigen_conversion`
If I can use `eigen_conversion`, conversions like `tf::vectorEigenToTF`->`tf::vector3TFToMsg` are simplified as `tf::vectorEigenToMsg` but it will be used only in https://github.com/start-jsk/rtmros_common/pull/896/files#diff-ac73db3c66ec2afe6e6410a14af1ebc0R845 and https://github.com/start-jsk/rtmros_common/pull/896/files#diff-ac73db3c66ec2afe6e6410a14af1ebc0R853

(3) Alternative implementations
We can remove `tf_conversion` dependency by removing `tf::Transform` class and using `Eigen::Affine3d` and so on. I think we have to use `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` macro in that case but I'm not t sure that this cause another problems or not. (However, components in hrpsys-base like ImpedanceController has Eigen classes as structure or class members. How do you avoid this problem? Some compilation options are needed?) and in this case, I think it is better that using `eigen_conversion` than directly insert to msg members to prevent insert mistakes.  It can be removed if we insert members of msg directly but then we have to pay attention to these mistakes.

**Comment by orikuma** [comment]
I talked with @snozawa in offline and I will rewrite PRs as follows:
(a) Requirements
- Suppressing `/tf` rate 
- Add following new transformations
  - `/odom`
  - `/odom_init`
  - `/ground`
  - `/body_on_odom`
- Add `/imu_rootlink` topic

(b) Implementation issues
- Do not use `tf::Transform` relatives and use Eigen libraries
- Consider `/odom` source (`baseRPY` from abc or kf and use joint angles of `rsangle` or `mcangle`)
- Consider using periodicTImerCallback or onExecute loop with counter to suppress `/tf` rate

**Comment by k-okada** [comment]
Could you describe definition of each frames? We'd like to put these in
https://github.com/ros-infrastructure/rep/blob/master/rep-0120.rst

2016年1月12日火曜日、Iori Kumagai<notifications@github.com>さんは書きました:

> I talked with @snozawa <https://github.com/snozawa> in offline and I will
> rewrite PRs as follows:
> (a) Requirements
>
>    - Suppressing /tf rate
>    - Add following new transformations
>       - /odom
>       - /odom_init
>       - /ground
>       - /body_on_odom
>    - Add /imu_rootlink topic
>
> (b) Implementation issues
>
>    - Do not use tf::Transform relatives and use Eigen libraries
>    - Consider /odom source (baseRPY from abc or kf and use joint angles
>    of rsangle or mcangle)
>    - Consider using periodicTImerCallback or onExecute loop with counter
>    to suppress /tf rate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/rtmros_common/pull/896#issuecomment-170893456>
> .
>


-- 
--
◉ Kei Okada

**Comment by orikuma** [comment]
Basic difinitions are described in https://github.com/jsk-ros-pkg/jsk_control/tree/master/jsk_footstep_controller .
I will describe details when the PRs for the new tfs are ready to be merged.

**Pull request closed without merging**
