### PR TITLE
Update euslisp hrpsysbase samples

### PR DESCRIPTION
**Pull request by snozawa**
Update euslisp examples for hrpsys-base. 

And then, add README.md for euslisp examples partially copied from ros wiki :
wiki.ros.org/rtmros_common/Tutorials/WorkingWithEusLisp.

I'll edit ros wiki to trace link of this github README.

### CODE REVIEW

**Comment by snozawa** [comment]
@k-okada or @YoheiKakiuchi 
Please review.

**Comment by k-okada** [comment]
some of original images has gone for example drc example. Is it ok?
your re basicall going to move wiki to github, but still have image file in
wiki server. is it safe?

--
◉ Kei Okada


2017-04-24 18:19 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
Thank you for your comments.

> some of original images has gone for example drc example. Is it ok? your re basicall going to move wiki to github, but still have image file in wiki server. is it safe?

Thanks, these are mis commit.
I'll fix it.
For the latter problem, I'll add the images of examples to rtmros_common.
The path may be `hrpsys_ros_bridge/test/hrpsys-samples/img`.

**Comment by snozawa** [comment]
> some of original images has gone for example drc example. Is it ok? your re basicall going to move wiki to github, but still have image file in wiki server. is it safe?

For adding the images, how about adding the images to hrpsys-base, not to rtmros_common?(if possible)

**Comment by k-okada** [comment]
seif you put images to hrpsys-base, you'd better to put cocd and doc to
hrpsys-base, doc, code, image should be put closer location

--
◉ Kei Okada


2017-04-25 12:34 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
Thanks.

> seif you put images to hrpsys-base, you'd better to put cocd and doc to hrpsys-base, doc, code, image should be put closer location

I already put the code and readme in hrpsys-base:
https://github.com/fkanehiro/hrpsys-base/tree/master/sample/SampleRobot
But, I found that the image is link of ros wiki page.
I'll fix it and improve hrpsys-base readme.

And then, the above hrpsys-base README is for hrpsys-base only and python interface.
We need euslisp + rtmros_common README and such readme is previously located in ros wiki : http://wiki.ros.org/rtmros_common/Tutorials/WorkingWithEusLisp
I'll move readme of this part (euslisp+rtmros_comomn) from ros wiki to rtmros_common.

**Comment by snozawa** [comment]
I created hrpsys-base PR:
https://github.com/fkanehiro/hrpsys-base/pull/1126

**Comment by snozawa** [comment]
@k-okada 
I update PR.
Main README.md is committed to upstream hrpsys-base:
https://github.com/fkanehiro/hrpsys-base/tree/master/sample/SampleRobot.

This PR is just a euslisp + rtmros example of the above hrpsys-base python examples.
This PR's images are links to hrpsys-base image files.

I added DRC example image.

**Comment by snozawa** [comment]
Thanks a lot!!

**Pull request merged**
