### PR TITLE
use setJointAnglesOfGroup() and playPattern(), use clearJointAngles()

### PR DESCRIPTION
**Pull request by k-okada**
this will enable cancelGoal of joint trajectory action server

[CAUTION!!!] this will use different API for limb controller, so we designed new API to have same functionality as old one, but it may change the behavior if there are bug.

### CODE REVIEW

**Comment by k-okada** [comment]
to : real robot owners : please check this PR before we merge.

**Comment by snozawa** [comment]
How can we test this?
```
(send *robot* :reset-maip-pose)
(send *ri* :angle-vector (send *robot* :angle-vector) 5000)
(read-line)
(send *ri* :cancel-angle-vector)
```

**Comment by k-okada** [comment]
that should work

on python

```
        larm = actionlib.SimpleActionClient("/larm_controller/joint_trajectory_action", JointTrajectoryAction)
        larm.wait_for_server()

        goal = JointTrajectoryGoal()
        goal.trajectory.header.stamp = rospy.get_rostime()
        goal.trajectory.joint_names.append("LARM_SHOULDER_P")
        goal.trajectory.joint_names.append("LARM_SHOULDER_R")
        goal.trajectory.joint_names.append("LARM_SHOULDER_Y")
        goal.trajectory.joint_names.append("LARM_ELBOW")
        goal.trajectory.joint_names.append("LARM_WRIST_Y")
        goal.trajectory.joint_names.append("LARM_WRIST_P")

        point = JointTrajectoryPoint()
        point.positions = [ x * math.pi / 180.0 for x in [30,30,30,-90,-40,-30] ]
        point.time_from_start = rospy.Duration(5.0)
        goal.trajectory.points.append(point)
        point = JointTrajectoryPoint()
        point.positions = [ x * math.pi / 180.0 for x in [0,0,0,0,0,0] ]
        point.time_from_start = rospy.Duration(10.0)
        goal.trajectory.points.append(point)
        print goal.trajectory.points
        larm.send_goal(goal)
        #larm.wait_for_result()                                                                                             
        time.sleep(3)
        larm.cancel_goal()                       
```

**Comment by k-okada** [comment]
これ，どうでしょうか？これがないとangle-vector-sequenceで送った後にcancelできないので，テレオペ等では有効だと思っているんですが．．．

**Comment by k-okada** [comment]
cc @terasawa

**Comment by 130s** [comment]
As I reported in https://github.com/tork-a/rtmros_nextage/issues/284#issuecomment-273788532 I confirmed that cancel command works with NEXTAGE on simulator. If any of Hironx/NEXTAGE Open users are interested in testing this on the real robot we're willing to help you.

**Comment by 130s** [comment]
I assume this doesn't require higher version of `hrpsys` (than the ones commonly used for NEXTAGE, 315.2.8 or to the least 315.1.9), looking at the functions in use, i.e. `setJointAnglesSequence`, `clearJointAngles`.

**Comment by k-okada** [comment]
https://github.com/fkanehiro/hrpsys-base/blob/315.1.9/idl/SequencePlayerService.idl
https://github.com/fkanehiro/hrpsys-base/blob/315.2.8/idl/SequencePlayerService.idl
https://github.com/fkanehiro/hrpsys-base/blob/master/idl/SequencePlayerService.idl
I do not think we have clearJointAngles function in old hrpsys,
1) need to update idl files to include information on version we can use
new featrue
2) it looks like we have clear/ clearNoWait fuction in old hrpsys, so may
be we can use that. need to look into more deeply.btw do we have test code
which checks this feature?

--
◉ Kei Okada


2017-01-27 2:50 GMT+09:00 Isaac I.Y. Saito <notifications@github.com>:

**Comment by 130s** [comment]
Sorry, looks like my comment https://github.com/start-jsk/rtmros_common/pull/765#issuecomment-275459268 was wrong. `clearJointAngles` was added to the upstream, hrpsys, in https://github.com/fkanehiro/hrpsys-base/pull/665 and `setJointAnglesSequence` in https://github.com/fkanehiro/hrpsys-base/pull/573. Both became available since 315.5.0 presumably.

**Comment by 7675t** [comment]
こちら，Kineticでビルドして試しましたが，軌道がおかしいのは直りましたが，動作のストップは効かないようです．hrpsysの方も https://github.com/fkanehiro/hrpsys-base/pull/1237 が必要ということでしょうか？ Kineticのhrpsysは以下です．

```
ii  ros-kinetic-hrpsys                               315.14.0-0xenial-20171104-182634-0800                 amd64        An OpenRTM-aist-based robot controller.
```

**Comment by k-okada** [comment]
You may not need  fkanehiro/hrpsys-base#1237 , because https://github.com/start-jsk/rtmros_common/pull/765/commits/a489f5f8342affd4ef69c0138acf3cf6611893d7 use old api for hrpsys < 315.16.0. Please check "Hrpsys viewer", because planned motion in rviz does not stop, when you push "stop" button, but that signal will send to hrpsys and stop execution

please also confirm if you can see folloinwg message, make sure that ROS bridge send 'clearOfGroup: rarm '.
```
[ INFO] [1518498649.682171977, 172.679999999]: [HrpsysSeqStateROSBridge0] @onExecutece 0 is working at 196[Hz] (exec 1261 Hz, dropped 196)
[ INFO] [1518498650.573884624, 173.529999999]: [HrpsysJointTrajectoryBridge0] @onFollowJointTrajectoryActionPreempt()
[ INFO] [1518498650.574057661, 173.529999999]: [HrpsysJointTrajectoryBridge0] clearOfGroup: rarm
```

**Comment by 7675t** [comment]
Sorry, this was my fault, the workspace setting was wrong.
I confirmed this PR works correctly with released packages in simulation, both with NXO and HIRO.
Thank you.

**Comment by aislab** [comment]
We tried this on real robot Hironx.
It was confirmed that it works correctly.

We tried it on ROS Kinetic.

**Comment by 7675t** [comment]
Great, thanks! @aislab @k-okada

**Comment by pazeshun** [comment]
@k-okada 
With this PR, `(send *ri* :cancel-angle-vector)` works with Hironx in JSK.

The behavior when a new command comes to follow joint trajectory action before the previous command is completed is also changed.
Before this PR, motion following the previous command is smoothly changed to follow the new command.
The previous command is not completed.
With this PR, motion following the previous command is immediately stopped and changed to follow the new command.

**Comment by Affonso-Gui** [comment]
@k-okada After including https://github.com/k-okada/rtmros_common/pull/10, can we merge this into master? Have been using in Hiro without problems.

**Comment by pazeshun** [comment]
> With this PR, motion following the previous command is immediately stopped and changed to follow the new command.

I found that this behaviour is due to `clear(OfGroup)` (old hrpsys).
When `clearJointAngles(OfGroup)` is used (new hrpsys), the robot smoothly stops.
This means HRP2 smoothly changes its motion after new command comes.

**Comment by pazeshun** [comment]
The contents of this PR were merged to master via #1071

**Pull request closed without merging**
