### PR TITLE
[WIP] Re-enable euslisp test on travis

### PR DESCRIPTION
**Pull request by pazeshun**
Currently, [euslisp test in hrpsys_ros_bridge](https://github.com/start-jsk/rtmros_common/blob/1.4.2/hrpsys_ros_bridge/CMakeLists.txt#L259-L263) doesn't run on travis.
This is because environment variable `IS_EUSLISP_TRAVIS_TEST` is not passed to jenkins.
~~This PR creates `IS_EUSLISP_TRAVIS_TEST` on jenkins using `BEFORE_SCRIPT`.~~

### CODE REVIEW

**Comment by pazeshun** [comment]
Currently on my laptop, `test-samplerobot-sequence-player-demo3` failed.
In addition, whole euslisp test takes about 13 minutes.
Travis test will probably fail.

**Comment by pazeshun** [comment]
> This PR creates `IS_EUSLISP_TRAVIS_TEST` on jenkins using `BEFORE_SCRIPT`.

I found that this cannot be done, because `BEFORE_SCRIPT` is executed on child process and cannot pass environment variables to parent process...:
https://github.com/jsk-ros-pkg/jsk_travis/blob/0.5.6/travis.sh#L299

**Comment by Naoki-Hiraoka** [comment]
https://github.com/start-jsk/rtmros_common/pull/1080#issuecomment-559970971

This is because of inconsistency of Force sensor order in samplerobot.

In key ```:wrench``` of ```:angle-vector-sequence-full```, the order is (rleg, lleg, rarm, larm).
https://github.com/start-jsk/rtmros_common/blob/4635cb5a58fa4aea51a9bbb36b6a010f1054927c/hrpsys_ros_bridge/CMakeLists.txt#L160

On the other hand, the order in the return value of  ```:force-sensors``` is (rarm, larm, rleg, lleg).
https://github.com/euslisp/jskeus/blob/b3d64f0f03dcd7c38642e20bb74c1f5006fd8385/irteus/demo/sample-robot-model.l#L132

How should we absorb this inconsistency?

**Comment by pazeshun** [comment]
Now euslisp tests are re-enabled thanks to https://github.com/jsk-ros-pkg/jsk_travis/pull/393.
Following four tests are changed.
- `USE_JENKINS=true ROS_DISTRO=hydro USE_DEB=source NOT_TEST_INSTALL=true EXTRA_DEB="ros-hydro-roseus ros-hydro-euscollada ros-hydro-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" IS_EUSLISP_TRAVIS_TEST="true"`
  - This test took 49 minutes on jenkins. Also, some euslisp tests failed (due to hydro environment?).
    - For the former problem, I'll split this test to two tests.
    - For the latter problem, I'll debug.
- `USE_JENKINS=true ROS_DISTRO=hydro USE_DEB=true EXTRA_DEB="ros-hydro-hrpsys-ros-bridge ros-hydro-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"`
  - Some euslisp tests failed due to the same reason as the above test.
- `USE_JENKINS=true ROS_DISTRO=hydro USE_DEB=false EXTRA_DEB="ros-hydro-hrpsys-ros-bridge ros-hydro-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"`
  - Some euslisp tests failed due to the same reason as the above test.
  ```
  <testsuite tests="5" failures="1" disabled="0" errors="0" time="3" name="AllTests">
    <testcase name="all-test" status="run" time="0" classname="all-test">
     <failure message="string expected" type="AssertionError">
  Test:(apply #'send ros::_feedback ros::__feedback)
  Trace:29
  Message:"string expected"
     </failure>
    </testcase>
    <testcase name="test-samplerobot-data-logger-init" status="run" time="3" classname="test-samplerobot-data-logger-init">
    </testcase>
    <testcase name="test-samplerobot-data-logger-demo0" status="run" time="0" classname="test-samplerobot-data-logger-demo0">
    </testcase>
    <testcase name="test-samplerobot-data-logger-demo1" status="run" time="0" classname="test-samplerobot-data-logger-demo1">
    </testcase>
    <testcase name="test-samplerobot-data-logger-demo2" status="run" time="0" classname="test-samplerobot-data-logger-demo2">
    </testcase>
  </testsuite>
  ```
- `USE_JENKINS=true ROS_DISTRO=indigo USE_DEB=false EXTRA_DEB="ros-indigo-hrpsys-ros-bridge ros-indigo-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"`
  - Passed.

**Comment by pazeshun** [comment]
> some euslisp tests failed

`(send *ri* :wait-interpolation)` doesn't seem to work:
```
1.irteusgl$ load "package://hrpsys_ros_bridge/euslisp/samplerobot-interface.l"

;; extending gcstack 0x5dcf210[32738] --> 0x69363a0[65476] top=7fe1
t
2.irteusgl$ samplerobot-init
[ WARN] [1575432289.894473108]: /use_sim_time is TRUE, check if /clock is pusblished or not
#<samplerobot-robot #X68fe948 SampleRobot  0.0 0.0 0.0 / 0.0 0.0 0.0>
3.irteusgl$ progn (send *sr* :reset-pose) (send *ri* :angle-vector (send *sr* :angle-vector) 2000)
#f(-0.004457 -21.6929 -0.01202 47.6723 -25.93 0.014025 17.8356 -9.13759 -6.61188 -36.456 0.0 0.0 0.0 -0.004457 -21.6929 -0.01202 47.6723 -25.93 0.014025 17.8356 9.13759 6.61188 -36.456 0.0 0.0 0.0 0.0 0.0 0.0)
4.irteusgl$ send *ri* :wait-interpolation
/opt/ros/hydro/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: string expected in (apply #'send ros::_feedback ros::__feedback)
```

**Comment by pazeshun** [comment]
Something is wrong in feedback subscription:
```
4.irteusgl$ ros::unsubscribe "fullbody_controller/joint_trajectory_action/feedback"
t
5.irteusgl$ progn (send *sr* :reset-pose) (send *ri* :angle-vector (send *sr* :angle-vector) 2000) (send *ri* :wait-interpolation)
(t)
```

**Comment by pazeshun** [comment]
I moved euslisp tests on hydro to `allow_failures`.
Instead, I added euslisp tests on kinetic.

**Comment by pazeshun** [comment]
Moved to #1085

**Pull request closed without merging**
