### PR TITLE
Remove all ros::object slots in def-set-get-param-method

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Removing all `ros::object` slots instead of `plist` and `_connection-header` in `def-set-get-param-method`, so that even if definition of `ros::object` changes in the future this code remains functional.
https://github.com/jsk-ros-pkg/jsk_roseus/pull/606

Also changing to use `symbol-name` instead of `format`. Strings get to uppercase, but since they are `read-string`ed afterwards should make no difference.

**>>Need testing<<**

Btw some random notes:
- I'm pretty sure that `string-left-trim` is not the right function here, specially if `rtc_name` may contain underscores.
https://github.com/start-jsk/rtmros_common/blob/0ac88687c3bb4dc9bf125ec869a24aea134b6580/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L236-L258
https://github.com/euslisp/EusLisp/issues/249
https://github.com/euslisp/EusLisp/issues/336

- `(elt ":" 0)` => `#\:`

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
@Naoki-Hiraoka @itohdak @mmurooka Can I ask help for testing with HRP2 simulation?

**Comment by Naoki-Hiraoka** [comment]
```:set-st-param```
がシミュレーションで問題なく動くことを確認しました

**Comment by pazeshun** [comment]
Waiting for #1080

**Comment by pazeshun** [comment]
#1085 is merged to master and master is merged to this PR.
No more WIP.

**Comment by pazeshun** [comment]
@k-okada 
This PR prevents such cases as #1053 
And this PR seems functional on real robot (thanks to #1075, #1079) and travis test (thanks to #1085).
Could you review this?

**Pull request merged**
