### PR TITLE
Add body on odom to HrpsysSeqStateROSBridge

### PR DESCRIPTION
**Pull request by orikuma**
This PR includes https://github.com/start-jsk/rtmros_common/pull/891
heightmap.launch needs body_on_odom

### CODE REVIEW

**Comment by orikuma** [comment]
Please check and merge if there is no problems.

**Comment by orikuma** [comment]
Integrate https://github.com/start-jsk/rtmros_common/pull/881

**Comment by snozawa** [comment]
I think this PR is too large and hard to check.
Could you divide this PR?
Or, could you tell us the URL for related PR?

For example, 
- PR just for re-naming and function separating, which is expected not to change the program behaviour.
- PR for adding new functionality. It would be better to include example code.
- PR for changing code with same behaviour. It would be better to include test code.
- ..etc

**Comment by orikuma** [comment]
This PR is devided into 8 parts, (0) #898 (1) #899 (2) #896 (3) #897 (4) #900 (5) #901 (6) #902 (7) #903

**Pull request closed without merging**
