### PR TITLE
Workaround for update .travis

### PR DESCRIPTION
**Pull request by garaemon**
1. use latest .travis
2. Run hydro test on jenkins.jsk

### CODE REVIEW

**Comment by garaemon** [comment]
Leave decision to @k-okada @130s 

* Pros:
  * Faster
     * More CPUs
     * More Memories
     * Use ccache to cache gcc object
     * Use apt-cacher-ng to cache apt
  * Robust
    * local network is more robust than travis

* Cons:
  * Depending on jsk infrastructure

**Comment by garaemon** [comment]
```
15:57:09 ImportError: "from catkin_pkg.topological_order import topological_order" failed: No module named tool_detection 
15:57:09 Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH. 
15:57:09 ++ exit 1                                                                       
15:57:09 terminate called after throwing an instance of 'CORBA::COMM_FAILURE'            
15:57:09 testtest_compile_idl_sh ... FAILURE!                                            
15:57:09 FAILURE: test [test_compile_idl_sh] did not generate test results               
15:57:09   File "/usr/lib/python2.7/unittest/case.py", line 327, in run                  
15:57:09     testMethod()                                                                
15:57:09   File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn 
15:57:09     self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name) 
15:57:09   File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue           
15:57:09     raise self.failureException(msg)                                            
15:57:09 -------------------------------------------------------------------------------- 
15:57:09 [ROSTEST]----------------------------------------------------------------------- 
15:57:09                                                                                 
15:57:09 [testtest_compile_idl_sh][failed]                                               
15:57:09                                                                                 
15:57:09 SUMMARY                                                                         
15:57:09  * RESULT: FAIL                                                                 
15:57:09  * TESTS: 0                                                                     
15:57:09  * ERRORS: 0                                                                    
15:57:09  * FAILURES: 1                                                                  
15:57:09                                                                                 
```

**Comment by garaemon** [comment]
@wkentaro Do you know how to fix the issue?

**Comment by wkentaro** [comment]
I don't know, but found https://github.com/jsk-ros-pkg/jsk_travis/issues/120 . 
maybe @k-okada knows about this .

**Comment by 130s** [comment]
> Run hydro test on jenkins.jsk

As far as I'm concerned (i.e. rtmros_hironx/NEXTAGE), we're no longer active on maintaining Hydro version. So I have no opinion about this.

**Comment by k-okada** [comment]
I'm afraid latest catkin may not work with hydro, is it correct?

--
◉ Kei Okada

**Comment by k-okada** [comment]
If you look at a few month from now
- we'll no longer uses hydro, (only if @garaemon passed the defence ;-)
- The reason we start using jenkins@jsk is for indigo test, and now
travis support indigo platform so we can move most of job back to the
travis.

Instability and time consumption of the hironx/nextage test is
frustrating hrpsys and rtmros_common users, so please look into this,
@130s
1) if it takes long time to compile rtmros_common, we can add an
option in hrpsys_ros_bridge/CMakeLists.txt to compile stable rtcs
only, for hironx/nextage test.
1) Increasing retry was not a good idea, it did not solved anything ->
https://github.com/start-jsk/rtmros_hironx/pull/376 ;

> As far as I'm concerned (i.e. rtmros_hironx/NEXTAGE), we're no longer active on maintaining Hydro version. So I have no opinion about this.

Current big problem is we do not have indigo test for rtmros_common
and we're not sure if  any commits on rtmros_common may break
hironx/nextage or not and
if we remove hironx/nextage test from rtmros_common, we'll realize
that breaks hironx/nextage after it is released. I'm afraid we can
handle this situation.
So having indigo test is essential and keeping  hydro test (from
source) may second best option.
--
◉ Kei Okada

**Comment by wkentaro** [comment]
please upgrade jsk_travis.

**Comment by 130s** [comment]
I'm afraid I might not understand something here, but sounds like we agreed for this PR?

> Instability and time consumption of the hironx/nextage test is frustrating hrpsys and rtmros_common users, so please look into this, @130s 
> 1) if it takes long time to compile rtmros_common, we can add an option in hrpsys_ros_bridge/CMakeLists.txt to compile stable rtcs only, for hironx/nextage test. 
> 2) Increasing retry was not a good idea, it did not solved anything -> start-jsk/rtmros_hironx#376 ;

I apologize if packages I maintain might have been causing headache, which I honestly did not know. Next time it happens please ping me so that I look at it.

**Comment by k-okada** [comment]
#934 supports jade / indigo test

**Pull request closed without merging**
