### PR TITLE
Add eigen tf conversions

### PR DESCRIPTION
**Pull request by orikuma**

### CODE REVIEW

**Comment by orikuma** [comment]
This PR result in same code as #895

**Comment by snozawa** [comment]
Please merge origin/master

**Comment by snozawa** [comment]
I'd like to know why we need to add `eigen_conversion` and `tf_conversion`.
In this PR, what are the conversions?
In HrpsysSeqStateROSBridge, you can use OpenHRP3-related libraries and Eigen.

**Comment by orikuma** [comment]
`eigen_conversion` is a library which provides methods to convert between eigen matrix and tf class and `tf_conversion` is a library which provides methods to convert geometry_msgs.
They are maintained by tf maintainers (https://github.com/ros/geometry).
OpenHRP3 related matrix libraries like hrp::Vector3 or hrp::Matrix33 which entities are Eigen have to be converted into geometry_msgs to publish as ros topic or transformations in /tf and tf::Transformation class is useful in converting Affine3d matrixes to rotation matrix, quaternion, translation vector tf::TransformationStamped and so on.
`tf_conversions` and `eigen_conversions` are used in these process.
It is also possible that we make msgs by directly inserting member slots, but I think it is too verbose.

**Comment by snozawa** [comment]
(A)
In this program, only the following line depends on `eigen_conversion` or `tf_conversion`:
```
   tf::matrixTFToEigen(base.getBasis(), R); // TODO: It is not good to assume hrp::Matrix33 is typedef of Eigen::Matrix3d implicitly (cf. EigenTypes.h) 
```
Maybe, you can use other functions without `eigen_conversions` or `tf_conversions`.
Please check this (comment out find_package and include of `eigen_conversions` and `tf_conversions` ... etc).

(B)
If this program takes tf input and converts tf input into eigen output, depending on `eigen_conversions` and `tf_conversions` are reasonable.
However, this program takes input from OpenRTM+OpenHRP3 programs and this program also includes libraries for that.
So, this program originally holds position and orientation information as OpenRTM+OpenHRP3 style, e.g., `hrp::Vector3` and `hrp::Matrix33`.
In your code, 
```
   tf::matrixTFToEigen(base.getBasis(), R); // TODO: It is not good to assume hrp::Matrix33 is typedef of Eigen::Matrix3d implicitly (cf. EigenTypes.h) 
```
rotation matrix from the tf instance `base` is copied to `hrp::Matrix33`.
But this `base.getBasis` originally comes from `rpy`, which is `hrp::vector3`:
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/HrpsysSeqStateROSBridge.cpp#L552

So, you are converting `hrp::Matrix33` -> `tf` -> `hrp::Matrix33` and this seem to unnecessary conversion.



If above comment is correct, please be careful to keep your code simple.

**Comment by orikuma** [comment]
I checked your comments and I'm sorry that it is correct that only one line depends on `eigen_conversions` in this PR .
This fault is caused by my incorrect division of #893 because this type of conversions are widely used after #896 .
Is it sufficient if I close this PR and merge this into #896?

**Comment by snozawa** [comment]
> Only fixing the inappropriate line will cause adding meaningless dependancy, so is it sufficient that I close this PR and merge this into #896?

Yes, we will move this discussion to #896.

**Pull request closed without merging**
