### PR TITLE
[hrpsys_ros_bridge] fix model filename

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
Enable cache in ModelLoader
filename should be same as in .conf file.

### CODE REVIEW

**Comment by snozawa** [comment]
I think this is no bad side-effect, is this true?

**Comment by YoheiKakiuchi** [comment]
I think so

**Comment by snozawa** [comment]
I see, thanks!

**Comment by k-okada** [comment]
> filename should be same as in .conf file.

how did you find this?

**Comment by YoheiKakiuchi** [comment]
> how did you find this?

launching hrpsys and ros_bridge at the same time failed  if using large wrl file (large mesh size or number of joints)  .
ros_bridge can be launched after starting hrpsys, but cache seems to be disabled
because of difference of filename, file://... or /...

**Pull request merged**
