### PR TITLE
Update for rtmros common test

### PR DESCRIPTION
**Pull request by snozawa**
Update for rtmros common test.

### CODE REVIEW

**Comment by snozawa** [comment]
Travis passed.

Fixed problems
- HrpsysSeqStateROSBridge variable initialization (moved from https://github.com/start-jsk/rtmros_common/pull/876)
- Reduce unnecessary sleep in sensor_ros_bridge.py
- Update travis to include PIP problem (https://github.com/start-jsk/rtmros_common/pull/876#issuecomment-164637271, https://github.com/jsk-ros-pkg/jsk_travis/pull/208/files) and mongodb setting (https://github.com/jsk-ros-pkg/jsk_travis/pull/216)
- Dirty workaround for test-samplerobot.test's hztest (https://github.com/start-jsk/rtmros_common/issues/877#issuecomment-164669534)

**Comment by snozawa** [comment]
> Dirty workaround for test-samplerobot.test's hztest (#877 (comment))

Debug memo

I could reproduce too small hztest problem on my PCs.
I increased `wait_time` and `test_duration`, but problem not solved.

I doubted frequency of hrpsys-simulator or HrpsyseqStateROSBridge.
I added `usleep` to both of them (like `usleep(10000)`) and HrpsysSeqStateROSBridge `[Hz]` printing became small.
But, problem cannot be reproduced by this usleep.

**Comment by k-okada** [comment]
On Wed, Dec 16, 2015 at 9:18 PM, Shunichi Nozawa <notifications@github.com>
wrote:

> I added usleep to both of them (like usleep(10000)) and
> HrpsysSeqStateROSBridge [Hz] printing became small.
> But, problem cannot be reproduced by this usleep.
>

do you mean adding usleep decrease Hz messe, but it did not fail on hztest?

--
◉ Kei Okada

**Comment by snozawa** [comment]
Sorry for late.

> do you mean adding usleep decrease Hz messe, but it did not fail on hztest?

Yes.
`[Hz]` print message from HrpsysSeqStateROSBridge is real-time Hz, which is different from simulation-time's Hz.
Even if real-time Hz is slow, hztest succeeded because it seem to check `clock`'s time originally derived from `hrpsys-simulator`.

**Comment by k-okada** [comment]
it is called 'Wall-Clock' (http://wiki.ros.org/Clock) and when you use
hrpsys-simulator, ros uses as same clock as hrpsys simuation cllock as
"simulaated clock", whcih was returnd by `ros::Time::now()`
And I think hz test checks on "simulated clock", sso adding sleep may not
work.

--
◉ Kei Okada

**Comment by snozawa** [comment]
> it is called 'Wall-Clock' (http://wiki.ros.org/Clock) and when you use hrpsys-simulator, ros uses as same clock as hrpsys simuation cllock as "simulaated clock", whcih was returnd by `ros::Time::now()` And I think hz test checks on "simulated clock", sso adding sleep may not work.

Yes, I thought so.
So I wanted to confirm some kinds of slowness of hrpsys-simulator or HrpsysSeqStateROSBridge execution does not influence on hztest error thanks for `Wall-Clock`.
https://github.com/start-jsk/rtmros_common/pull/879#issuecomment-165090121 shows hztest error is not derived from slowness of execution.

**Pull request merged**
