### PR TITLE
Add cmake setting and euscollada yaml for special joint robot.

### PR DESCRIPTION
**Pull request by snozawa**
Add cmake setting and euscollada yaml for special joint robot.

### CODE REVIEW

**Comment by snozawa** [comment]
https://github.com/fkanehiro/openhrp3/pull/80
passed.

**Comment by k-okada** [comment]
what is special joint?

**Comment by snozawa** [comment]
Sorry for late reply.

In this case, "special joint" means not simple rotational joint and linear joint.
https://github.com/fkanehiro/openhrp3/pull/80
Openhrp3 supports 1-dof rotational joint and linear joint, free and fixed joints.
This robot is defined by 1dof rotational joint, but this robot is used for hrpsys-base testing for special use cases, currently:
- Leg more than 6 dof
- Interlocking joint (mimic joint)
- Fly wheel joint on upper body

**Comment by k-okada** [comment]
I see, so this is complex structured robot.
special joint sounds like something not X, but this definition is not clear and I'm afriad we'll have "special joint 2" or "new special joint"

**Comment by snozawa** [comment]
> so this is complex structured robot.

Should I rename the robot?

> special joint sounds like something not X, but this definition is not clear and I'm afriad we'll have "special joint 2" or "new special joint" 

When I added "special joint robot" in openhrp3, I considered the following two choices:
- (A) Adding "special joint robot"
- (B) Adding "toe joint robot", "multi-dof leg robot", "fly wheel robot", ... independently.

Using (B), we need to write and maintain many files than (A).
So I choose (A).
If we'd like to test new joint feature, we do not need to add "special joint2" and we just need to
 add new joint feature to "spcial joint".

Is it better to use (B)?
(becasue file names in (B) is more clear than (A).)

**Comment by k-okada** [comment]
I think this discussion may clear way you named "special joint" for this 
case, so I think it is ok for now.

--
◉ Kei Okada

**Pull request merged**
