### PR TITLE
Revert "compile_robot contains output files, not targets"

### PR DESCRIPTION
**Pull request by k-okada**
Reverts start-jsk/rtmros_common#700

### CODE REVIEW

**Comment by garaemon** [comment]
hironx-ros-bridge test fails

**Comment by k-okada** [comment]
waiting for this ...
http://jenkins.ros.org/job/ros-hydro-hironx-ros-bridge_sourcedeb/

--
◉ Kei Okada

**Comment by k-okada** [comment]
@eisoku9618 , please update rtmros_common to pass rtmros_hrp2

**Comment by eisoku9618** [comment]
passed!

**Pull request merged**
