### PR TITLE
[hrpsys_ros_bridge] publish hand joint states in SeqStateRosBridge

### PR DESCRIPTION
**Pull request by mmurooka**
rtcのポートから受け取ったハンド関節角をjoint_states_handとしてpublishします。

### CODE REVIEW

**Comment by garaemon** [comment]
:+1

**Comment by k-okada** [comment]
-1
- there are no generic hand status publisher plugin
- this has to set hand joint information via rosparam, but that information
should be set somewhere else to run hand rtc. (if you change hand
configuration you have to fix rtc hand plugin launcher and bridge launcher)

--
◉ Kei Okada

**Comment by 534o** [comment]
We can think of
1. Create hand specific bridge
2. Put hand bridge into seqstaterosbridge
3. Publish robot state including hand status in hrpsys
4. Create rtc port - ros topic bridge

I think we should choose 3 or 4, 3 can enable collision check the including hand in hrpsys, 4 is very general

**Comment by k-okada** [comment]
We can think of
1. Create hand specific bridge
2. Put hand bridge into seqstaterosbridge
3. Publish robot state including hand status in hrpsys
4. Create rtc port - ros topic bridge

I think we should choose 3 or 4, 3 can enable collision check the including hand in hrpsys, 4 is very general

**Comment by mmurooka** [comment]
こちら別の方法でやるということで一旦closeします．

**Comment by mmurooka** [comment]
cc @iory

**Pull request closed without merging**
