### PR TITLE
[hrpsys_ros_bridge] Fix genjava problem by adding message_generation …

### PR DESCRIPTION
**Pull request by wkentaro**
…as build_depend

Edited:

 - hrpsys_ros_bridge/package.xml

### CODE REVIEW

**Comment by YuOhara** [comment]
https://github.com/start-jsk/rtmros_common/issues/878

**Comment by snozawa** [comment]
Please merge origin/master

**Comment by k-okada** [comment]
```
]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6>> hcf.setJointAngles([10,10,10,10,10,10,10,10,10], 1) 
]2;[build] 6/6Traceback (most recent call last):      
]2;[build] 6/6  File "/home/travis/ros/ws_rtmros_common/src/rtmros_common/hrpsys_tools/scripts/hrpsys_tools_config.py", line 44, in <module> 
]2;[build] 6/6    exec(args.c[0])                     
]2;[build] 6/6  File "<string>", line 1, in <module>  
]2;[build] 6/6  File "/home/travis/ros/ws_rtmros_common/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 991, in setJointAngles 
]2;[build] 6/6    return self.seq_svc.setJointAngles(ret, tm) 
]2;[build] 6/6  File "/home/travis/ros/ws_rtmros_common/devel/lib/python2.7/dist-packages/hrpsys/SequencePlayerService_idl.py", line 137, in setJointAngles 
]2;[build] 6/6    return _omnipy.invoke(self, "setJointAngles", _0_OpenHRP.SequencePlayerService._d_setJointAngles, args) 
]2;[build] 6/6omniORB.CORBA.OBJECT_NOT_EXIST: CORBA.OBJECT_NOT_EXIST(omniORB.OBJECT_NOT_EXIST_NoMatch, CORBA.COMPLETED_NO) 
]2;[build] 6/6]2;[build] 6/6terminate called after throwing an instance of 'CORBA::OBJECT_NOT_EXIST' 
]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6]2;[build] 6/6testhrpsys_tool_config_interactive ... FAILURE! 
]2;[build] 6/6FAILURE: test [hrpsys_tool_config_interactive] did not generate test results 
]2;[build] 6/6  File "/usr/lib/python2.7/unittest/case.py", line 327, in run 
]2;[build] 6/6    testMethod()                        
]2;[build] 6/6  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn 
]2;[build] 6/6    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name) 
]2;[build] 6/6  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue 
]2;[build] 6/6    raise self.failureException(msg)    
]2;[build] 6/6-------------------------------------------------------------------------------- 
]2;[build] 6/6                                        
]2;[build] 6/6[ROSTEST]----------------------------------------------------------------------- 
]2;[build] 6/6                                        
]2;[build] 6/6[testhrpsys_tool_config_interactive][failed] 
]2;[build] 6/6                                        
]2;[build] 6/6SUMMARY                                 
]2;[build] 6/6 * RESULT: FAIL                         
]2;[build] 6/6 * TESTS: 0                             
]2;[build] 6/6 * ERRORS: 0                            
]2;[build] 6/6 * FAILURES: 1    
```
restarted travis

**Comment by k-okada** [comment]
Closes #878

**Comment by k-okada** [comment]
closes #878

**Pull request merged**
