### PR TITLE
[WIP][.travis.yml] use travis in all tests instead of jenkins.

### PR DESCRIPTION
**Pull request by mmurooka**
related to https://github.com/start-jsk/rtmros_common/pull/973#issuecomment-254130314.

### CODE REVIEW

**Comment by furushchev** [comment]
we cannot use travis directly on `kinetic`, please consider to use `USE_DOCKER=true`. (refer: https://github.com/jsk-ros-pkg/jsk_travis/blob/master/.travis.yml#L51)
And I think it is simpler that declare `USE_DOCKER=true` globally for testing of all distros.

**Comment by furushchev** [comment]
As far as I see what you are discussing on https://github.com/start-jsk/rtmros_common/pull/973#issuecomment-254130314, when testing on docker on travis, we need to configure each environment variables to pass to docker ( https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L78-L91 ) like jenkins unfortunatelly.

**Comment by mmurooka** [comment]
travisの結果のメモ

hydroはtravisだと失敗．

indigoでは環境変数`IS_EUSLISP_TRAVIS_TEST`がわたってroseusのテストが走る．
https://travis-ci.org/start-jsk/rtmros_common/jobs/168202321
> [hrpsys_ros_bridge:cmake] Execute rostest for euslisp unittest

jenkinsだとダメでtravisだとOKなので，https://github.com/start-jsk/rtmros_common/pull/973#issuecomment-254130314 で合っていた．
ただ，50分で終わらない．

**Comment by pazeshun** [comment]
@mmurooka
こちらについてですが、#1085 において、`IS_EUSLISP_TRAVIS_TEST`をjenkinsに渡すことで、euslispのテストがjenkinsでも走るようにしました。
もしこれで大丈夫でしたら、こちらのcloseをお願いします。

**Comment by mmurooka** [comment]
ありがとうございます．

**Pull request closed without merging**
