### PR TITLE
Add more CORBA exception information.

### PR DESCRIPTION
**Pull request by snozawa**
Add more CORBA exception information.
Add BAD_PARAM and OBJECT_NOT_EXIST and add minor code.

(memo)
```
しぬとき
COMM_FAILURE
ないぶにもんだい
BAD_PARAM
sinda ato
OBJECT_NOT_EXIST

http://software.fujitsu.com/jp/manual/manualfiles/M050008/B1WN5901/01Z200/apgod05/apgod106.htm
http://www.nec.co.jp/WebOTX/download/manual/85/html/msg/5_corba.html
```

### CODE REVIEW

**Comment by snozawa** [comment]
In this PR, I added more information about exception.
There many subclass in `CORBA::SystemException` and currently I added `BAD_PARAM` and `OBJECT_NOT_EXIST`.
http://software.fujitsu.com/jp/manual/manualfiles/M050008/B1WN5901/01Z200/apgod05/apgod106.htm
http://www.nec.co.jp/WebOTX/download/manual/85/html/msg/5_corba.html

In our robot (jaxon), for example,
- Some error occurs within rtc's Service function (such as `setAutoBalancerparam`) and hrpsys process does not die. => `BAD_PARAM`
- hrpsys process die becasue of rtc's service port function calling => `COMM_FAILURE`
- Try to call rtc's service port function after dying hrpsys process => `OBJECT_NOT_EXIST`

**Comment by k-okada** [comment]
Nice!

How about add following insight to the error message , like "xx exception; This is likely message type mismatch, please make sure that you are using same version of Idl for both server and client side" or something 
```
Some error occurs within rtc's Service function (such as setAutoBalancerparam) and hrpsys process does not die. => BAD_PARAM
hrpsys process die becasue of rtc's service port function calling => COMM_FAILURE
Try to call rtc's service port function after dying hrpsys process => OBJECT_NOT_EXIST
```

**Comment by snozawa** [comment]
> How about add following insight to the error message

Sounds good.
I'll update PR.

**Comment by snozawa** [comment]
Updated and I added IDL mismatch case:

- Some error occurs within rtc's Service function (such as setAutoBalancerparam) and hrpsys process does not die. => BAD_PARAM
- hrpsys process die becasue of rtc's service port function calling => COMM_FAILURE
- Try to call rtc's service port function after dying hrpsys process => OBJECT_NOT_EXIST
- IDL mismatch => COMM_FAILURE or MARSHAL? (different in several case?)

**Pull request merged**
