### PR TITLE
Use latest hrpsys when hrpsys is built on kinetic, in case libpcl-dev and libopenni2-dev exist

### PR DESCRIPTION
**Pull request by pazeshun**
Includes #1092 

We want to use source of released hrpsys, but building it fails on kinetic when libpcl-dev and libopenni2-dev exist.
Until https://github.com/fkanehiro/hrpsys-base/pull/1242 is released on kinetic, we have to use latest hrpsys on kinetic.
Details: https://github.com/start-jsk/rtmros_common/pull/1090#issuecomment-610860446

Also, I found some typos in README which I overlooked at #1090 , so this PR fixes them and format README.
Sorry for overlooking.

### CODE REVIEW

**Comment by Naoki-Hiraoka** [comment]
I checked this PR works with source of openhrp3 and hrpsys on kinetic in my laptop.
Thank you!

```
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src
wstool init .
wstool set rtmros_common https://github.com/start-jsk/rtmros_common --git -y
wstool merge https://raw.githubusercontent.com/start-jsk/rtmros_common/master/.travis.rosinstall -y
wstool merge https://raw.githubusercontent.com/start-jsk/rtmros_common/900c79e005a77a1544716eabb5f921aacca2a9ed/.travis.rosinstall.kinetic -y
wstool update 
cd ..
source /opt/ros/kinetic/setup.bash
rosdep install -r --from-paths src --ignore-src -y
catkin build
source devel/setup.bash
rtmlaunch hrpsys_ros_bridge samplerobot.launch 
```

**Comment by pazeshun** [comment]
There is some misunderstanding, so I updated #1092 and this PR.

**Comment by pazeshun** [comment]
Travis test with `USE_DEB=false` failed on kinetic:
```
[Testcase: testhrpsys_tool_config_interactive] ... FAILURE!



                                                                                
FAILURE: Test Fixture Nodes ['hrpsys'] failed to launch


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run



                                                                                
    testMethod()


                                                                                
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn


                                                                                
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue


                                                                                
    raise self.failureException(msg)
```
```
[Testcase: testhztest_tf] ... FAILURE!


                                                                                
FAILURE: Test Fixture Nodes ['hrpsys'] failed to launch



                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run


                                                                                
    testMethod()


                                                                                
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn


                                                                                
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue


                                                                                
    raise self.failureException(msg)


                                                                                
--------------------------------------------------------------------------------


                                                                                
[Testcase: testpa10] ... FAILURE!


                                                                                
FAILURE: Test Fixture Nodes ['hrpsys'] failed to launch


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run


                                                                                
    testMethod()


                                                                                
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn


                                                                                
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue


                                                                                
    raise self.failureException(msg)
```
and so on.
@Naoki-Hiraoka Please be careful, this PR may not be complete.

**Comment by pazeshun** [comment]
I understand what is happening.
The reason why the test fails is that hrpsys-simulator is not compiled.
This is caused by racking of `libopencv-dev`.

The error message in my previous comment says the node `hrpsys` doesn't exist.
This node is hrpsys-simulator in hrpsys package (declared [here](https://github.com/start-jsk/rtmros_common/blob/1.4.2/hrpsys_tools/launch/hrpsys.launch#L122-L125)).
hrpsys-simulator is compiled only when OpenCV was found by `pkg_check_modules` (see [here](https://github.com/fkanehiro/hrpsys-base/blob/5cbb5490f55c7017f7ff789c3d9de531ba92e1b6/util/CMakeLists.txt#L3-L4) and [here](https://github.com/fkanehiro/hrpsys-base/blob/5cbb5490f55c7017f7ff789c3d9de531ba92e1b6/CMakeLists.txt#L163-L172), note that we are using linux, not APPLE).
To install OpenCV by rosdep, dependency to `cv_bridge` is written in package.xml (see [here](https://github.com/fkanehiro/hrpsys-base/blob/5cbb5490f55c7017f7ff789c3d9de531ba92e1b6/package.xml#L30))

However, on kinetic, `cv_bridge` depends on `opencv3` (see [here](https://github.com/ros-perception/vision_opencv/blob/kinetic/cv_bridge/package.xml#L23)), while it depends on `libopencv-dev` on [indigo](https://github.com/ros-perception/vision_opencv/blob/indigo/cv_bridge/package.xml#L23) and [melodic](https://github.com/ros-perception/vision_opencv/blob/melodic/cv_bridge/package.xml#L23).
So rosdep installs `opencv3` on kinetic.
As described [here](http://wiki.ros.org/opencv3#Usage), **find_package(OpenCV)** can find `opencv3`, but we use **pkg_check_modules(OpenCV opencv)** which cannot find `opencv3` (I'm not sure its reason, but the behavior implies that).
This causes skipping of compiling hrpsys-simulator.

This is already known issue, so hrpsys for releasing on kinetic depends on `libopencv-dev` directly instead of `cv_bridge` (see [here](https://github.com/tork-a/hrpsys-release/commit/f9a0f08b000e71f15165b1d25e9b97e54fdca936)).
So far, we doesn't face the issue thanks to using released hrpsys, but this PR changes it to original hrpsys and the issue emerges again.

**Comment by pazeshun** [comment]
Though I'm not sure why [the fixing commit](https://github.com/tork-a/hrpsys-release/commit/f9a0f08b000e71f15165b1d25e9b97e54fdca936) is not in any pull requests to original hrpsys, I think merging that commit to original hrpsys is straight and easy fix, because changing `pkg_check_modules` to `find_package` is drastic and we have to check in many platforms.

Merging to original hrpsys may take long time, so we need some temporary fix.
I think we should install `libopencv-dev` explicitly on travis using `EXTRA_DEBS` and add instruction to install `libopencv-dev` manually in README.
Another solution is to add `libopencv-dev` to dependency of `hrpsys_tools`, but it seems strange.

**Comment by pazeshun** [comment]
@Naoki-Hiraoka I solved the issue and travis passed.
Maybe your current environment already includes `libopencv-dev`, so there is no problem, but be careful when you change your environment.

**Comment by Naoki-Hiraoka** [comment]
I understand. Thank you !

**Pull request merged**
