### PR TITLE
[hrpsys_ros_bridge] Add ":set-foot-steps-with-param-and-base-height"

### PR DESCRIPTION
**Pull request by garaemon**
method in order to specify footstep with params and base height

### CODE REVIEW

**Comment by garaemon** [comment]
@snozawa BTW, I think we need better way to specify base height with footsteps...

**Comment by snozawa** [comment]
I see...

**Comment by snozawa** [comment]
Please merge origin/master
https://github.com/start-jsk/rtmros_common/pull/815

**Comment by snozawa** [comment]
３番一応とおってますが、４７分くらいで、まだ危ないですね。

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_travis/pull/143

これを試すと時間が減るかも、しれない

**Pull request merged**
