### PR TITLE
Update .travis to the latest jsk_travis

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
Currently a lot of pull request fails on travis.
We need to fix it.

**Comment by garaemon** [comment]
```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
```

install command of hrpsys/openrtm/openhrps generates a lot of messages

**Comment by garaemon** [comment]
```
The following packages have unmet dependencies:
 ros-hydro-hironx-ros-bridge : Depends: ros-hydro-hrpsys-ros-bridge but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Cannot install hrpsys-ros-bridge

**Comment by garaemon** [comment]
So we have two problems on travis:
1. too long messages
2. deb of hrpsys-ros-bridge is broken

**Comment by k-okada** [comment]
1. https://travis-ci.org/start-jsk/rtmros_common/builds/50494195
2. https://github.com/start-jsk/rtmros_common/issues/595

And you can merge your PR even if test fails, if you re confident

2015年2月13日金曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> So we have two problems on travis:
> 1. too long messages
> 2. deb of hrpsys-ros-bridge is broken
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/rtmros_common/pull/652#issuecomment-74115262>
> .
>


-- 
--
◉ Kei Okada

**Comment by garaemon** [comment]
> 1. https://travis-ci.org/start-jsk/rtmros_common/builds/50494195

I don't understand what you want to mean. Do you mean test exceeds 50 minutes and we should disable it?

**Comment by k-okada** [comment]
close since #654 cover this

**Pull request closed without merging**
