### PR TITLE
Add emergency walking stop

### PR DESCRIPTION
**Pull request by snozawa**
Add emergency walking stop.

### CODE REVIEW

**Comment by k-okada** [comment]
not related to this PR but something wrong (
https://travis-ci.org/start-jsk/rtmros_common/jobs/67361619)

```
]2;[build] 12/15]2;[build] 12/15[hrpsys_ros_bridge_tutorials] [ 92%] Generating /home/travis/ros/ws_rtmros_common/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/HRP2JSKNTS_body.urdf 
]2;[build] 12/15]2;[build] 12/15]2;[build] 12/15]2;[build] 12/15]2;[build] 12/15[hrpsys_ros_bridge_tutorials] [ 92%] Generating /home/travis/ros/ws_rtmros_common/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/HRP2JSKNTS_WH.urdf 
]2;[build] 12/15]2;[build] 12/15]2;[build] 12/15[hrpsys_ros_bridge_tutorials] Traceback (most recent call last):                
]2;[build] 12/15[hrpsys_ros_bridge_tutorials]   File "/opt/ros/hydro/share/xacro/xacro.py", line 60, in <module> 
]2;[build] 12/15[hrpsys_ros_bridge_tutorials]     xacro.main()                                  
]2;[build] 12/15[hrpsys_ros_bridge_tutorials]   File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 657, in main 
]2;[build] 12/15[hrpsys_ros_bridge_tutorials]     process_includes(doc, os.path.dirname(args[0])) 
]2;[build] 12/15[hrpsys_ros_bridge_tutorials]   File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 268, in process_includes 
]2;[build] 12/15[hrpsys_ros_bridge_tutorials]     % (filename, str(e)))                         
]2;[build] 12/15[hrpsys_ros_bridge_tutorials] xacro.XacroException: included file "/home/travis/ros/ws_rtmros_common/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/HRP2JSKNTS_body.urdf" generated an error during XML parsing: no element found: line 1076, column 1 
]2;[build] 12/15[hrpsys_ros_bridge_tutorials] make[2]: *** [/home/travis/ros/ws_rtmros_common/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials/models/HRP2JSKNTS_WH.urdf] Error 1 
]2;[build] 12/15[hrpsys_ros_bridge_tutorials] make[1]: *** [CMakeFiles/HRP2JSKNTS_xacro_model_generate.dir/all] Error 2 
```

**Comment by snozawa** [comment]
Is this travis log message of this PR?
Or, other PR's travis log?

**Comment by k-okada** [comment]
This is the log of master branch that runs after this PR was merged
On master branch we check with private repo, which PR did not

from
https://github.com/start-jsk/rtmros_common/pull/719
we're checking rtmros_hrp2 only for master branch
( so if you create PR on master branch not your forked branch, the it will
be tested)

--
◉ Kei Okada

2015/06/19 21:34、Shunichi Nozawa <notifications@github.com> のメッセージ:

Is this travis log message of this PR?
Or, other PR's travis log?

—
Reply to this email directly or view it on GitHub
<https://github.com/start-jsk/rtmros_common/pull/754#issuecomment-113500766>
.

**Comment by snozawa** [comment]
I see, it seems `hrpsys_ros_bridge_tutorials` parallel processing bug.
I found that the following command errors in my PC and almost same error occurs:
`roscd hrpsys_ros_bridge_tutorials && git clean -xfd && catkin bt --force-cmake`.

If I use catkin build with `-j 1`, it always success.

**Comment by k-okada** [comment]
Thanks 

Update Travis test to check this issue 
https://github.com/start-jsk/rtmros_hrp2/pull/240

By the way, will it fail to compile with -j2 ? If not how about -j4?

--
◉ Kei Okada

2015/06/20 14:44、Shunichi Nozawa <notifications@github.com> のメッセージ:

**Comment by snozawa** [comment]
> By the way, will it fail to compile with -j2 ? If not how about -j4?

Yes, `-j > 1` always seems to fail.
Only `-j 1` always succeed.

**Comment by k-okada** [comment]
humm, https://magnum.travis-ci.com/start-jsk/rtmros_hrp2/jobs/19275195 uses "-j2 -l2" and not fails

**Comment by k-okada** [comment]
I can not reproduce this error on my PC 
what did you see bottom right while you're compiling the source code 
```[N/N Jobs | N/N Active | N/N Completed]```

**Comment by snozawa** [comment]
I obtain the message like this : `[2/8 Jobs | 1/8 Active | 12/13 Completed]`.
(``roscd hrpsys_ros_bridge_tutorials && git clean -xfd . && catkin bt --start-with-this --force-cmake``)

At the beginning of catkin build, message was `[8/8 Jobs | 1/8 Active | 12/13 Completed]`.
This may correspond to `compile_robot_model` execution.

After that, message changes to `[2/8 Jobs | 1/8 Active | 12/13 Completed]`.
This may correspond to urdf generation and modification.
At this moment, failure occurs.


I may fix this problem through https://github.com/start-jsk/rtmros_tutorials/pull/326.

**Comment by k-okada** [comment]
It seems you're compiling with -j 8, is it correct?

--
◉ Kei Okada

2015/06/20 17:40、Shunichi Nozawa <notifications@github.com> のメッセージ:

**Comment by snozawa** [comment]
Yes, i think so (cpu number is 8 and catkin build use cpu number by default).
https://github.com/start-jsk/rtmros_tutorials/pull/326 is expected to success even if `-j 8`.

**Pull request merged**
